# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'R.swift'

  pod 'GoogleAnalytics'
  pod 'GoogleAppMeasurement'
  pod 'GoogleAppMeasurementOnDeviceConversion'
  pod 'Repro'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/RemoteConfig'

  # Pods for mynavi-baito-foreign
  pod 'RNCryptor'

  pod 'GoogleMaps'

  # Carthageから移行
  pod 'Adjust'
  pod 'Adjust/Criteo'
  pod 'KeychainAccess'
  pod 'CryptoSwift'

  pod 'APNGKit'
  pod 'Kingfisher'
  pod 'PKHUD'
  pod 'Toast-Swift'
  pod 'RealmSwift'

  # include Alamofire
  pod 'Moya'

  pod 'RxSwift'
  pod 'RxCocoa'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
